"""empty message

Revision ID: 4007ed8ceabc
Revises: 8d86acae1c95
Create Date: 2019-11-11 16:19:13.579189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4007ed8ceabc'
down_revision = '8d86acae1c95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column(
        'seeking_description', sa.String(), nullable=True))
    op.add_column('Artist', sa.Column(
        'seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('website', sa.String(), nullable=True))
    op.add_column('Venue', sa.Column(
        'genres', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column(
        'seeking_description', sa.String(), nullable=True))
    op.add_column('Venue', sa.Column(
        'seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('website', sa.String(), nullable=True))

    op.execute(
        'UPDATE "Artist" SET seeking_description = \'\' WHERE seeking_description IS NULL;')
    op.execute(
        'UPDATE "Artist" SET seeking_venue = False WHERE seeking_venue IS NULL;')
    op.execute('UPDATE "Artist" SET website = \'\' WHERE website IS NULL;')
    op.execute('UPDATE "Artist" SET genres = \'\' WHERE genres IS NULL;')
    op.execute('UPDATE "Venue" SET genres = \'\' WHERE genres IS NULL;')
    op.execute(
        'UPDATE "Venue" SET seeking_description = \'\' WHERE seeking_description IS NULL;')
    op.execute(
        'UPDATE "Venue" SET seeking_talent = False WHERE seeking_talent IS NULL;')
    op.execute('UPDATE "Venue" SET website = \'\' WHERE website IS NULL;')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'website')
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Venue', 'seeking_description')
    op.drop_column('Venue', 'genres')
    op.drop_column('Artist', 'website')
    op.drop_column('Artist', 'seeking_venue')
    op.drop_column('Artist', 'seeking_description')
    # ### end Alembic commands ###
